# Generated by Django 4.0.5 on 2022-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ism',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='qarz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='kelgan_narx',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='miqdor',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='sotuv_narx',
            field=models.IntegerField(),
        ),
    ]
