# Generated by Django 4.0.5 on 2022-06-07 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ombor',
            name='ism',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ombor',
            name='tel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ombor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
